// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjzdslyumkjcjkcsqlpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqemRzbHl1bWtqY2prY3NxbHBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODc3NjYsImV4cCI6MjA2NjM2Mzc2Nn0.FeMT-9SLmIWt2bePRTT9fAP7or66ljiiNc7knNn30mI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);